project:
  type: website
  output-dir: docs

website:
  title: "FISH 470 Lab"
  site-url: "https://sarahtanja.github.io/fish470-lab/"
  repo-url: "https://sarahtanja.github.io/fish470-lab/"

page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Modules
        
format:
  html:
    preview: true
    theme: journal
    highlight-style: github
    page-layout: article
    code-background: true
    code-tools: 
      source: true
      toggle: true
    toc: true
    toc-depth: 2
    toc-location: right
    df-print: kable
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    reference-location: margin
    citation-location: margin
