project:
  type: website
  output-dir: docs

website:
  title: "FISH 470 Lab"
  navbar:
    left:
      - href: modules.qmd
        text: Modules

format:
  gfm: 
    toc: true
    number-sections: true
  html:
    preview: true
    theme: journal
    highlight-style: github
    page-layout: article
    code-background: true
    code-tools: 
      source: true
      toggle: true
    toc: true
    toc-depth: 2
    toc-location: left
    df-print: kable
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    reference-location: margin
    citation-location: margin
